### ISSUE TITLE
What is the best test accuracy in your Implementation? 

### ISSUE THREAD

**Issue by FriedaSmith** [KrishnaDN/Emotion-Identification-from-Raw-Speech-Signals-using-TDNNs#3]
Hi. What is the best **test accuracy** in your Implementation? Why is my test accuracy only **53%**?

**Comment by KrishnaDN** [comment]
> Hi. What is the best **test accuracy** in your Implementation? Why is my test accuracy only **53%**?

Hi, According to the paper, the best accuracy they have reported is 56% UA and 59% WA. These numbers are reported after training with augmented data (adding volume and noise perturbation). According to the paper, you should get 6-7% boost up in accuracy if you add noise perturbation. In the current implementation, we don't have perturbation implementation. So, 53% accuracy is still reasonable I think
